name: Bug
description: Report a bug
type: Bug
body:
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, and other relevant details
    validations:
      required: false
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: cause-suggestion
    attributes:
      label: Cause, Suggestion
    validations:
      required: false
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      value: |
        - [ ] task
    validations:
      required: false
